name: Trigger GitLab CI

on: [push, pull_request] 

jobs:
  trigger-gitlab-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger pipeline on CFD-Xing/gitlab-ci
      uses: CFD-Xing/x3d2@main
      with:
        url: https://gitlab.nektar.info
        project_id: 364
        token: ${{ secrets.GITLABCI }}
        variables: |
          VAR1=value1
          VAR2=value2
